import React from "react";
import Head from "next/head";

const MainLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
        <nav>{/* Navbar */}</nav>
      </header>
      <main>{children}</main>
      <footer>{/* Footer */}</footer>
    </>
  );
};

export default MainLayout;
